// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDS55ybacIZIoKWBR7rwoAU-GQDSzL_0',
    appId: '1:82829353401:web:febffe2239b3854f011668',
    messagingSenderId: '82829353401',
    projectId: 'excelsync-8d4a2',
    authDomain: 'excelsync-8d4a2.firebaseapp.com',
    databaseURL: 'https://excelsync-8d4a2-default-rtdb.firebaseio.com',
    storageBucket: 'excelsync-8d4a2.appspot.com',
    measurementId: 'G-DDM14HCYNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcOYJBjZSMQKth3-xgR10fS_syNZJ8wlw',
    appId: '1:82829353401:android:da8a7abf12dfb901011668',
    messagingSenderId: '82829353401',
    projectId: 'excelsync-8d4a2',
    databaseURL: 'https://excelsync-8d4a2-default-rtdb.firebaseio.com',
    storageBucket: 'excelsync-8d4a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmK_W7_ubUC1YvxthI_S3C2CLIzxh_ic',
    appId: '1:82829353401:ios:7db98f95237f5ce5011668',
    messagingSenderId: '82829353401',
    projectId: 'excelsync-8d4a2',
    databaseURL: 'https://excelsync-8d4a2-default-rtdb.firebaseio.com',
    storageBucket: 'excelsync-8d4a2.appspot.com',
    iosBundleId: 'com.example.cockpitintelligence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGmK_W7_ubUC1YvxthI_S3C2CLIzxh_ic',
    appId: '1:82829353401:ios:f9936dfa574869cd011668',
    messagingSenderId: '82829353401',
    projectId: 'excelsync-8d4a2',
    databaseURL: 'https://excelsync-8d4a2-default-rtdb.firebaseio.com',
    storageBucket: 'excelsync-8d4a2.appspot.com',
    iosBundleId: 'com.example.cockpitintelligence.RunnerTests',
  );
}
